### PR TITLE
Fixes hydration warnings

### LINKED ISSUE #27: Header Merge Fixes
The merge of the header component created some minor issues, I lets fix these, including Next.js warnings.

### PR DESCRIPTION
**Pull request by skoly1**

### CODE REVIEW

File: app/layout.tsx [hunk 1]
```diff
@@ -27,8 +27,10 @@ export default function RootLayout({
                     disableTransitionOnChange
                     themes={['light', 'dark']}
                 >
-                    {/* <Header /> */}
-                    <StoreProvider>{children}</StoreProvider>
+                    <StoreProvider>
+                        <Header />
```
Comment (adamrichardturner) [inline app/layout.tsx:31]: Nice, back in!

File: app/layout.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ export default function RootLayout({
     children: React.ReactNode
 }>) {
     return (
-        <html lang='en'>
+        <html lang='en' suppressHydrationWarning>
```
Comment (adamrichardturner) [inline app/layout.tsx:21]: Ah yes, I missed this. Usually there as a boilerplate for me

**Review by adamrichardturner — APPROVED** [review]
Looks good!
